import Head from "next/head";
import Image from "next/image";
import Me from "../public/images/company.jpg";
import { BsInstagram, BsWhatsapp } from "react-icons/bs";
import { FaTelegram } from "react-icons/fa";
import { GrLinkedinOption } from "react-icons/gr";
import { useContext } from "react";
import { themeContext } from "@/contexts/ThemeContext";
import { motion } from "framer-motion";
import { useRouter } from "next/router";
import React from "react";
import Social from "./Social";
interface Props {
    setSelect: React.Dispatch<React.SetStateAction<number>>;
}

// href="https://join.skype.com/invite/iF0Cjsce2cyB"
export default function Home({ setSelect }: Props) {
    const { theme } = useContext(themeContext);
    return (
        <>
            <Head>
                <title>رزومه</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <motion.div
                initial={{ y: 900, opacity: 0, transitionDuration: "1.4s" }}
                animate={{ y: 0, opacity: 1 }}
                className={`${
                    theme === "dark" ? "" : "bg-[url('../public/images/background.jpg')]"
                } w-full h-full bg-center bg-cover flex-col-reverse relative flex px-10 lg:flex-row -mt-20 lg:mt-0 justify-center items-center gap-20`}
            >
                <div className="flex flex-col gap-10 -mt-10 lg:mt-0">
                    <div className="space-y-2">
                        {" "}
                        <p className="font-yekanLight text-xs dark:text-gray-400">
                            سلام، من{" "}
                            <span className="font-ykanExtraBold text-xl text-gray-800 dark:text-white px-2">علی قانع فرد</span>{" "}
                            هستم
                        </p>
                        <p className="text-xs font-yekanMedium dark:text-gray-400">
                            <span>طراح وب از </span>
                            <span className="text-orange-500"> استان خراسان رضوی</span>
                        </p>
                    </div>
                    <p className="font-yekanRegular text-xs text-gray-400">
                        من برنامه نویس طراح وب از استان خ.ر هستم، می توانید منو در شبکه های اجتماعی دنبال کنید
                    </p>
                    <Social />
                    <button
                        onClick={() => setSelect(1)}
                        className="font-ykanExtraBold text-[14px] w-32 py-2 text-white rounded-lg  bg-orange-600"
                    >
                        درباره من
                    </button>
                </div>
                <Image src={Me} alt="" className="rounded-full mt-24 lg:mt-0 w-[150px] h-[150px] lg:w-[350px] lg:h-[350px]" />
            </motion.div>
        </>
    );
}
